[package]
name = "four_using_unsafe_code_impl_split_at_mut"
version = "0.1.0"
authors = ["LongLe <v.longlx4@vinid.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
