[package]
name = "three_lifetime_annotations_in_struct"
version = "0.1.0"
authors = ["LongLe <xuanlongvts@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
